version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: ${PG_HOST} 
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASSWORD}
      DB_DATABASE: ${PG_DATABASE}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: p2-frontend
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: ${BACKEND_URL}
